// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2017-09-21 ( Time 16:30:29 )

import { Injectable } from '@angular/core';

@Injectable()
export class Configuration {
    public server = 'http://localhost:3000';
    public apiUrl = '/api/v1/';
    public serverWithApiUrl = this.server + this.apiUrl;
}
